application:
  port:
    default: 3000
  image:
    name: 782662248973.dkr.ecr.us-east-1.amazonaws.com/tech-challenge-app
    tag: latest
  service:
    type: LoadBalancer
    ports:
      protocol: TCP
      port: 80
  hpa:
    minReplicas: 1
    maxReplicas: 10
    metrics:
      type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
