apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-deployment
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-api-deployment
      labels:
        app: {{ .Release.Name }}-api-deployment
    spec:
      containers:
        - name: {{ .Release.Name }}-api-deployment
          image: {{ .Values.application.image.name }}:{{ .Values.application.image.tag }}
          ports:
            - containerPort: {{ .Values.application.port.default }}
          env:
            - name: MY_SETTINGS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-api-settings
                  key: settings.json
          livenessProbe:
            httpGet:
              path: /api/category
              port: {{ .Values.application.port.default }}
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /api/category
              port: {{ .Values.application.port.default }}
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          resources:
            limits:
              memory: 512Mi
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api-deployment
