apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-api-deployment
  minReplicas: {{ .Values.application.hpa.minReplicas }}
  maxReplicas: {{ .Values.application.hpa.maxReplicas }}
  metrics:
    - type: {{ .Values.application.hpa.metrics.type }}
      resource:
        name: {{ .Values.application.hpa.metrics.resource.name }}
        target:
          type: {{ .Values.application.hpa.metrics.resource.target.type }}
          averageUtilization: {{ .Values.application.hpa.metrics.resource.target.averageUtilization }}
