apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc-api
  labels:
    app: {{ .Release.Name }}-svc-api
spec:
  selector:
    app: {{ .Release.Name }}-api-deployment
  type: {{ .Values.application.service.type }}
  ports:
    - port: {{ .Values.application.service.ports.port }}
      protocol: {{ .Values.application.service.ports.protocol }}
      targetPort: {{ .Values.application.port.default }}
