apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: {{ .Values.database.volume.storageClassName }}
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/opt/data/postgres'
    type: DirectoryOrCreate
