apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.service.name }}
  labels:
    app: {{ .Values.database.service.name }}
spec:
  ports:
    - port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}
  selector:
    app: {{ .Release.Name }}-db-deployment
