database:
  port: 5432
  replicas: 1
  config:
    PostgresDB: postgres
    PostgresUser: postgres
    PostgresPassword: root
  volume:
    storageClassName: manual
  image:
    name: 782662248973.dkr.ecr.us-east-1.amazonaws.com/tech-challenge-db
    tag: latest
  service:
    name: svc-tech-challenge-db
